### ISSUE TITLE
LSP not working on Windows because of file extension

### ISSUE THREAD

**Issue by Dimension4** [tonis2/c3-vscode#1]
It seems the LSP cannot start on Windows because the LSP exe doesn't have a file extension. I've manually renamed `c3-lsp-windows` to `c3-lsp-windows.exe` and adjusted the path in `extension.js` and now it seems to work fine. Not sure why VS Code needs a file extension, running the LSP from the terminal worked fine, even before.

I would open a PR, but I don't know where you get the binaries from, so I can't rename them.

**Comment by tonis2** [comment]
Thanks for the notice, fixed and pushed to vscode.

I take the LSP binaries here https://github.com/pherrymason/c3-lsp/releases
