### ISSUE TITLE
The lsp binary has changed, need to update to reflect

### ISSUE THREAD

**Issue by joshring** [tonis2/c3-vscode#11]
From: https://github.com/pherrymason/c3-lsp.git

> Binary name changed to c3lsp (before it was c3-lsp).

An example needing an update

```json
"c3lspclient.lsp.path": {
	"type": "string",
	"default": null,
	"markdownDescription": "The path to **c3-lsp** binary"
},
```

**Comment by tonis2** [comment]
Is it just a description name update or something else too ?
Fixed it [here](https://github.com/tonis2/c3-vscode/blob/main/package.json#L57)
